language: cpp
compiler:
  - gcc
  - clang
before_install: ./scripts/travis/install-deps.sh
install: sudo apt-get install scons
script: scons
env:
  global:
    - JSONCPP_CONTINUOUS_INTERATION=1
  matrix:
    - SHARED_LIBRARY=ON BUILD_TYPE=release VERBOSE_MAKE=false
    - SHARED_LIBRARY=OFF BUILD_TYPE=release VERBOSE_MAKE=false
    - SHARED_LIBRARY=OFF BUILD_TYPE=debug VERBOSE VERBOSE_MAKE=true
